### PR TITLE
A way to handle region specific s3 buckets

### PR DESCRIPTION
**Pull request by runningdeveloper**
When I used the elastic beanstalk GUI it made me a region specific s3 bucket. So its like this ```bucketname.s3.af-south-1.amazonaws.com``` rather than ```bucketname.s3.amazonaws.com```. When deploying the current action failed when running the ```checkIfFileExistsInS3``` and ```uploadFileToS3``` function.

I'm not sure if this is the best way to do it. But the following works for me.
Let me know if you have ideas to improve.

Thanks for making the action.

### CODE REVIEW

**Comment by einaregilsson** [comment]
Thanks for the pull request. How did you make this bucket in the GUI? Did you create the sample application, or use the "Upload your code" button?

**Comment by runningdeveloper** [comment]
Yes I did the create sample initially. Then from there used the upload code and then started trying CI stuff.

**Comment by einaregilsson** [comment]
I'll have to think about this one. I don't want to add endless options, but I can still see it can be useful. In the meantime you can always use your fork, and maybe in the next official release I might merge it in

**Comment by runningdeveloper** [comment]
Yeah totally agree with less options. You can leave this out. If it affects others in future we can add a note in the readme.

**Pull request closed without merging**
