### PR TITLE
Add exponential backoff

### PR DESCRIPTION
**Pull request by n-hebert**
Working to resolve #74

### CODE REVIEW

**Comment by n-hebert** [comment]
Still needs more testing.

**Comment by einaregilsson** [comment]
Ok, let me know when it's done and I'll merge it. I looked at the code, looks good :)

**Comment by einaregilsson** [comment]
Hmmm, actually, thinking about it some more, it might be a better approach to actually put the exponential backup logic inside the aws-api-request.js file itself, it would keep the application logic cleaner maybe. I need to think about it some more.

**Comment by einaregilsson** [comment]
Made an attempt at https://github.com/einaregilsson/beanstalk-deploy/pull/75/files 

Making the backoff there should apply to all operations that are used, so the beanstalk-deploy.js shouldn't have to worry about retries. Still need to remove throttling logic from beanstalk-deploy.js and actually test this, for now it's just my first idea about where to put it.

**Comment by n-hebert** [comment]
Sounds good here!
I'd happily co-work & test on your branch.

My branch isn't working for some reason. I'm very new to JavaScript dev, especially with Promises.

**Pull request closed without merging**
